stages {

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Testing..."'
            }
        }
    }
}

stage('Build') {
  steps {
    sh 'mvn clean install'
  }
}


stage('Test') {
  steps {
    sh 'mvn test'
  }
}
