
http {
    ...
    limit_req_zone $binary_remote_addr zone=rate:10m rate=50r/s;
    server {
        ...
        location / {
            limit_req zone=rate burst=20;
            ...
        }
    }
}
