# Script generated by AstroCode
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--name', type=str)
parser.add_argument('--age', type=int)
args = parser.parse_args()
print(f'Name: {args.name}, Age: {args.age}')
